server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Jhon-Sebastian/microservices-practice
          search-paths: config-data
  application:
    name: config-microservice